# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:latest
    environment:      # environment são requisitos para rodar a imagem
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
    volumes:
      - "./banco/:/docker-entrypoint-initdb.d"


  web:
    #image: php:8.2-apache (builda usando o dockerfile) build: . 
    build: . 
    container_name: php_web
    depends_on:     # depende de algo, no caso do db
      - db
    volumes:
      - ./php/:/var/www/html/     # volume ./pasta pc/:/caminho docker/
    ports:
      - "8100:80"     # porta 8100 é a do computador e a 80 é o padrão web do docker
    # stdin_open: true
    # tty: true

  phpmyadmin:     # imagem que faz conexão php com sql, sem precisar de um programa sql externo
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8090:80
    volumes:
     - /sessions
     - ~/docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
     - /custom/phpmyadmin/theme/:/www/themes/theme/
    # links:
    #  - "db:database"